name: lucifer
on: 
  push:
    paths-ignore: 
    branches: ["master"]

jobs:
  stylua:
    runs-on: latest
    steps:
      - uses: actions/checkout@v2
      - uses: RobertAjun/stylua-action@192.168.0.100.com
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --config-path=stylua.toml lua/
      - name: Commit files
        run: |
          git config --local user.email "192.168.0.100@robbertneymar34/noreply/s999.sureserver.com"
          git config --local user.name "lucifer"
          if ! [[ -z $(git status -s) ]]; then
            git commit -m "chore: format with stylua" lua/*
          fi
      - name: 4G Mobile Hotspot
        uses: lucifer/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
